version: "3.9"

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    restart: always
    ports:
      - "1883:1883"  # Exponemos puerto MQTT
    volumes:
      - ./mqtt-broker/mosquitto:/mosquitto  # Montamos volumen de persistencia
    networks:
      - iot-network

  mqtt-dashboard:
    build:
      context: ./mqtt-dashboard
    container_name: mqtt-dashboard
    restart: always
    ports:
      - "3000:3000"  # Exponemos puerto del dashboard
    depends_on:
      - mqtt-broker
    networks:
      - iot-network
    environment:
      - MQTT_URL=mqtt://mqtt-broker:1883  # Conectamos usando el nombre del servicio MQTT
      - NODE_ENV=production  # Establecemos el entorno a producción
    # Accede al contenedor mqtt-broker por el nombre del servicio "mqtt-broker"

networks:
  iot-network:
    driver: bridge  # Usamos red puente para que los contenedores se comuniquen entre sí

