version: "3.9"  # Define la versión de Docker Compose

services:
  # Servicio MQTT Broker (Mosquitto)
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    restart: always
    ports:
      - "1883:1883"  # MQTT (puerto 1883)
    volumes:
      - ./mqtt-broker/mosquitto:/mosquitto  # Montar el volumen para persistencia
    networks:
      - iot-network

  # Servicio del servidor Node.js (mqtt-dashboard)
  mqtt-dashboard:
    build:
      context: ./mqtt-dashboard  # Directorio donde está el Dockerfile de Node.js
    container_name: mqtt-dashboard
    restart: always
    ports:
      - "3000:3000"  # Puerto para el dashboard (web)
    depends_on:
      - mqtt-broker  # Espera a que el broker esté listo
    networks:
      - iot-network
    environment:
      - MQTT_URL=mqtt://mqtt-broker:1883  # URL del broker MQTT dentro de la red interna

networks:
  iot-network:
    driver: bridge  # Red interna para que los contenedores puedan comunicarse
